***1. Suppose you have a dataset containing daily temperature readings for a city, and you want to identify days with extreme temperature conditions. Find days where the temperature either exceeded 35 degrees Celsius (hot day) or dropped below 5 degrees Celsius (cold day).***

In [109]:
import numpy as np

temp = np.array([32.5, 34.2, 36.8, 29.3, 31.0, 38.7, 23.1, 18.5, 22.8, 37.2, 4.0, 27.2, 24.0, -4.0, -12.0])
print("Hot Days:")
header = f"{'Day'.ljust(10)}{'temperatur(°C)'.rjust(5)}"
print(header)
hot_days = np.where(temp>35)[0]
for day in range(len(hot_days)):
    print(f"{hot_days[day]+1}         {temp[hot_days][day]}")

print("\nCold Days:")
header2 = f"{'Day'.ljust(10)}{'temperatur(°C)'.rjust(5)}"
print(header2)
cold_days = np.where(temp<5)[0]
for days in range(len(cold_days)):
    print(f"{cold_days[days]+1}         {temp[cold_days][days]}")

Hot Days:
Day       temperatur(°C)
3         36.8
6         38.7
10         37.2

Cold Days:
Day       temperatur(°C)
11         4.0
14         -4.0
15         -12.0


***2. Suppose you have a dataset containing monthly sales data for a company, and you want to split this data into quarterly reports for analysis and reporting purposes.***

In [110]:
import numpy as np

monthly_sales = np.array([120, 135, 148, 165, 180, 155, 168, 190, 205, 198, 210, 225])

Quarter_Sale = np.split(monthly_sales,4)

i = 1
for sales in Quarter_Sale:
        print("Quarter",i,"Sales (in thousands of dollars):\n",sales)
        i+=1

Quarter 1 Sales (in thousands of dollars):
 [120 135 148]
Quarter 2 Sales (in thousands of dollars):
 [165 180 155]
Quarter 3 Sales (in thousands of dollars):
 [168 190 205]
Quarter 4 Sales (in thousands of dollars):
 [198 210 225]


***3. Suppose you have a dataset containing customer data, and you want to split this data into two groups: one group for customers who made a purchase in the last 30 days and another group for customers who haven't made a purchase in the last 30 days.***

In [111]:
import numpy as np

customer_ids = np.array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])
last_purchase_days_ago = np.array([5, 15, 20, 25, 30, 35, 40, 45, 50, 55])

act_mask = last_purchase_days_ago<=30
act_cust = customer_ids[act_mask]
inact_cust = customer_ids[~act_mask]

print(f"Active Customers (Last Purchase <= 30 days ago):\n{act_cust}")
print(f"Inactive Customers (Last Purchase >30 days ago):\n{inact_cust}")

Active Customers (Last Purchase <= 30 days ago):
[101 102 103 104 105]
Inactive Customers (Last Purchase >30 days ago):
[106 107 108 109 110]


***4. Suppose you have two sets of employee data—one containing information about full-time employees and another containing information about part-time employees. You want to combine this data to create a comprehensive employee dataset for HR analysis.***


In [112]:
import numpy as np

full_time_employees = np.array([[101, 'John Doe', 'Full-Time', 55000],
    [102, 'Jane Smith', 'Full-Time', 60000],
    [103, 'Mike Johnson', 'Full-Time', 52000]])

part_time_employees = np.array([[201, 'Alice Brown', 'Part-Time', 25000],
    [202, 'Bob Wilson', 'Part-Time', 28000],
    [203, 'Emily Davis', 'Part-Time', 22000]])

combined_data = np.vstack((full_time_employees, part_time_employees))

print("Combined Employee Data:")
for data in combined_data:
    print(f"Employee ID: {data[0]}, Name: {data[1]}, Type: {data[2]}, Salary: {data[3]}")

Combined Employee Data:
Employee ID: 101, Name: John Doe, Type: Full-Time, Salary: 55000
Employee ID: 102, Name: Jane Smith, Type: Full-Time, Salary: 60000
Employee ID: 103, Name: Mike Johnson, Type: Full-Time, Salary: 52000
Employee ID: 201, Name: Alice Brown, Type: Part-Time, Salary: 25000
Employee ID: 202, Name: Bob Wilson, Type: Part-Time, Salary: 28000
Employee ID: 203, Name: Emily Davis, Type: Part-Time, Salary: 22000


***5. How to find the mean of every NumPy array in the given list?***

***Input:***
    
    list = [
        np.array([3, 2, 8, 9]),
        np.array([4, 12, 34, 25, 78]),
        np.array([23, 12, 67])
    ]

In [113]:
import numpy as np 

list = [
        np.array([3, 2, 8, 9]),
        np.array([4, 12, 34, 25, 78]),
        np.array([23, 12, 67])
    ]
final =[]
for i in list:
        mean_each = np.mean(i)
        final.append(mean_each)
print("Mean of Each array\n",final)

Mean of Each array
 [5.5, 30.6, 34.0]


***6. Compute the median of the flattened NumPy array***

***Input:***
    
    x_odd = np.array([1, 2, 3, 4, 5, 6, 7])

In [114]:
import numpy as np

x_odd = np.array([1, 2, 3, 4, 5, 6, 7])
print("Printing the Original array:\n",x_odd)

x_med = np.median(x_odd)
print("Median of the array that contains odd no of elements:\n",x_med)

Printing the Original array:
 [1 2 3 4 5 6 7]
Median of the array that contains odd no of elements:
 4.0


***3.Compute the standard deviation of the NumPy array***

***Input:***

    arr = [20, 2, 7, 1, 34]

In [115]:
import numpy as np

arr = [20, 2, 7, 1, 34]
print("arr : ", (arr))
arr_stand1 = np.std(arr)
print("Std of arr : ",arr_stand1)
arr_stand2 = np.std((arr),dtype = np.float32)
print("\nMore precision with float32\nStd of arr : ",arr_stand2)
arr_stand3 = np.std((arr),dtype = np.float64)
print("\nMore accuracy with float64\nStd of arr : ",arr_stand3)


arr :  [20, 2, 7, 1, 34]
Std of arr :  12.576167937809991

More precision with float32
Std of arr :  12.576168

More accuracy with float64
Std of arr :  12.576167937809991
