### ***1. Convert the below list into numpy array then display the array***

***input***
    
    my_list = [1,2,3,4,5]

***Output***
    
    Numpy array: [1 2 3 4 5]

In [2]:
# 1. Convert the below list into numpy array then display the array

import numpy as np

my_list = np.array([1,2,3,4,5])
print("Numpy array: ",my_list)

Numpy array:  [1 2 3 4 5]


### ***2. Convert the below list into a numpy array then display the array then display the first and last index and then multiply each element by 2 and display the result***

***input***

    my_list = [1,2,3,4,5]

***Output***

    First element: 1

    Last element: 5

    Array after doubling each element:
    [2 4 6 8 10]

In [3]:
# 2. Convert the below list into a numpy array then display the array then display the first and last index and then multiply each element by 2 and display the result

import numpy as np

my_list = np.array([1,2,3,4,5])
print("First element: ",my_list[0])
print("Last element: ",my_list[len(my_list)-1])
print("Array after doubling each element:\n",my_list*2)

First element:  1
Last element:  5
Array after doubling each element:
 [ 2  4  6  8 10]


### ***3. Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives***

***Sample Output***

    An array of 10 zeros
    [0 0 0 0 0 0 0 0 0 0]

    An array of 10 ones 
    [1 1 1 1 1 1 1 1 1 1] 

    An array of 10 fives
    [5 5 5 5 5 5 5 5 5 5]

In [4]:
# 3. Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives

import numpy as np

arr = np.zeros((10),dtype = np.int8)
print("An array of 10 zeros\n",arr)
arr2 = np.zeros((10),dtype = np.int8)+1
print("An array of 10 ones\n",arr2)
arr3 = np.zeros((10),dtype = np.int8)+5
print("An array of 10 fives\n",arr3)

An array of 10 zeros
 [0 0 0 0 0 0 0 0 0 0]
An array of 10 ones
 [1 1 1 1 1 1 1 1 1 1]
An array of 10 fives
 [5 5 5 5 5 5 5 5 5 5]


### ***4. . Winte a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.***

***Sample Output***

    [[2 9 7]
    [2 8 5]
    [4 5 2]]

In [5]:
# 4. . Winte a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

import numpy as np

np.random.seed(2)
arr = np.random.randint(2,10,(3,3))
print(arr)

[[2 9 7]
 [2 8 5]
 [4 5 2]]
