1. Hi! I am new to Python numpy. Can you generate some real world situations where I can use a nilimpy array with some source code.

In [45]:
import numpy as np

np.random.seed(11)
temp = np.random.uniform(1,50,30)
hot_temp = temp>=25
cold_temp = temp<15
normal_temp = (temp>=15) & (temp<25)
hot = np.where(hot_temp)[0]
hot_day = temp[hot_temp]
normal = np.where(normal_temp)[0]
normal_day = temp[normal_temp]
cold = np.where(cold_temp)[0]
cold_day = temp[cold_temp]
print(",  ".join(f"{x:.2f}"for x in temp))
print("\nHot Dates of the Month:")
for i in range(len(hot)):
    print(f"Day {hot[i] + 1}: {hot_day[i]:.2f}°C")
print("\nNormal Dates of the Month:")
for i in range(len(normal)):
    print(f"Day {normal[i] + 1}: {normal_day[i]:.2f}°C")
print("\nCold Dates of the Month:")
for i in range(len(cold)):
    print(f"Day {cold[i] + 1}: {cold_day[i]:.2f}°C")


9.83,  1.95,  23.70,  36.52,  21.59,  24.79,  1.63,  24.88,  47.15,  42.69,  36.77,  6.33,  44.80,  43.00,  9.09,  31.98,  2.00,  6.72,  16.50,  8.74,  38.19,  41.10,  17.89,  16.62,  6.47,  5.11,  35.92,  30.38,  3.73,  24.51

Hot Dates of the Month:
Day 4: 36.52°C
Day 9: 47.15°C
Day 10: 42.69°C
Day 11: 36.77°C
Day 13: 44.80°C
Day 14: 43.00°C
Day 16: 31.98°C
Day 21: 38.19°C
Day 22: 41.10°C
Day 27: 35.92°C
Day 28: 30.38°C

Normal Dates of the Month:
Day 3: 23.70°C
Day 5: 21.59°C
Day 6: 24.79°C
Day 8: 24.88°C
Day 19: 16.50°C
Day 23: 17.89°C
Day 24: 16.62°C
Day 30: 24.51°C

Cold Dates of the Month:
Day 1: 9.83°C
Day 2: 1.95°C
Day 7: 1.63°C
Day 12: 6.33°C
Day 15: 9.09°C
Day 17: 2.00°C
Day 18: 6.72°C
Day 20: 8.74°C
Day 25: 6.47°C
Day 26: 5.11°C
Day 29: 3.73°C


2. Hi Let's create a real-life example involving weather data. Use NumPy to analyze temperature data for a week, perform slicing, indexing, shaping, and reshaping operations, and calculate various statistics.

In [46]:
import numpy as np

np.random.seed(11)

temps = np.around(np.random.uniform(15, 35, (7, 4)), decimals=2)
humidity = np.around(np.random.uniform(40, 90, (7, 4)), decimals=2)
days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
times = ["Morning", "Afternoon", "Evening", "Night"]

print("Temperature Data for the Week:")
print(temps)

print("\nHumidity Data for the Week:")
print(humidity)

#Indexing
monday_temps = temps[0]
monday_humidity = humidity[0]
print(f"\nTemperatures on Monday: {monday_temps}")
print(f"Humidity on Monday: {monday_humidity}")

#Slicing
afternoon_temps = temps[:, 1]
afternoon_humidity = humidity[:, 1]
print(f"\nAfternoon Temperatures: {afternoon_temps}")
print(f"Afternoon Humidity: {afternoon_humidity}")

#Reshape
reshaped_temps = temps.reshape(4, 7)
reshaped_humidity = humidity.reshape(4, 7)
print(f"\nReshaped Temperature Data (4x7):\n{reshaped_temps}")
print(f"\nReshaped Humidity Data (4x7):\n{reshaped_humidity}")

#Various statistics
mean_temp = np.mean(temps)
median_temp = np.median(temps)
std_temp = np.std(temps)

mean_humidity = np.mean(humidity)
median_humidity = np.median(humidity)
std_humidity = np.std(humidity)

print(f"\nMean Temperature: {mean_temp}°C")
print(f"Median Temperature: {median_temp}°C")
print(f"Standard Deviation of Temperature: {std_temp:.2f}°C")

print(f"\nMean Humidity: {mean_humidity:.2f}%")
print(f"Median Humidity: {median_humidity:.2f}%")
print(f"Standard Deviation of Humidity: {std_humidity:.2f}%")

max_temp = np.max(temps)
min_temp = np.min(temps)

max_humidity = np.max(humidity)
min_humidity = np.min(humidity)

print(f"\nMaximum Temperature: {max_temp}°C")
print(f"Minimum Temperature: {min_temp}°C")

print(f"\nMaximum Humidity: {max_humidity}%")
print(f"Minimum Humidity: {min_humidity}%")

hottest_time_index = np.argmax(np.mean(temps, axis=0))
coldest_time_index = np.argmin(np.mean(temps, axis=0))
print(f"\nHottest Time of the Day: {times[hottest_time_index]}")
print(f"Coldest Time of the Day: {times[coldest_time_index]}")

most_humid_time_index = np.argmax(np.mean(humidity, axis=0))
least_humid_time_index = np.argmin(np.mean(humidity, axis=0))
print(f"\nMost Humid Time of the Day: {times[most_humid_time_index]}")
print(f"Least Humid Time of the Day: {times[least_humid_time_index]}")


Temperature Data for the Week:
[[18.61 15.39 24.26 29.5 ]
 [23.4  24.71 15.26 24.75]
 [33.84 32.02 29.6  17.17]
 [32.88 32.14 18.3  27.65]
 [15.41 17.33 21.33 18.16]
 [30.18 31.37 21.89 21.38]
 [17.23 16.68 29.25 26.99]]

Humidity Data for the Week:
[[42.78 63.99 60.08 82.4 ]
 [75.89 70.1  67.62 87.46]
 [89.33 56.9  51.99 79.82]
 [43.18 58.23 43.5  55.97]
 [43.52 54.51 79.51 85.27]
 [79.63 68.09 70.8  58.07]
 [48.44 61.81 76.64 43.14]]

Temperatures on Monday: [18.61 15.39 24.26 29.5 ]
Humidity on Monday: [42.78 63.99 60.08 82.4 ]

Afternoon Temperatures: [15.39 24.71 32.02 32.14 17.33 31.37 16.68]
Afternoon Humidity: [63.99 70.1  56.9  58.23 54.51 68.09 61.81]

Reshaped Temperature Data (4x7):
[[18.61 15.39 24.26 29.5  23.4  24.71 15.26]
 [24.75 33.84 32.02 29.6  17.17 32.88 32.14]
 [18.3  27.65 15.41 17.33 21.33 18.16 30.18]
 [31.37 21.89 21.38 17.23 16.68 29.25 26.99]]

Reshaped Humidity Data (4x7):
[[42.78 63.99 60.08 82.4  75.89 70.1  67.62]
 [87.46 89.33 56.9  51.99 79.82 43.18 5