## **Numpy**<hr/>

NumPy, which stands for **"Numerical Python,"** is a popular Python library for numerical and scientific computing. It provides support for working with large, multi-dimensional arrays and matrices of data, along with a collection of mathematical functions to operate on these arrays.

NumPy is a fundamental library for data manipulation and analysis in Python and is widely used in various fields such as data science, machine learning, scientific research, and engineering.

### **ndim**<hr/>

it is used to get the dimension of the array

In [13]:
import numpy as ny

a = ny.array(42)
b = ny.array([1,2,3,4,5])
c = ny.array([[1,2,3],[4,5,6]])

print(a.ndim)
print(b.ndim)
print(c.ndim)

print(a)
print(b)
print(c)


0
1
2
42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### **shape**<hr/>

It is used to provide the dimensions of the array

In [14]:
import numpy as ny

a = ny.array(42)
b = ny.array([1,2,3,4,5])
c = ny.array([[1,2,3],[4,5,6]])
d = ny.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)


()
(5,)
(2, 3)
(2, 2, 3)


In [54]:
import numpy as np

arr = np.array([True,False,True],dtype = np.int32)
print(arr)

[1 0 1]


In [49]:
import numpy as np

arr = np.array(['apple',1,2.3],dtype = np.bool_)
print(arr)

[ True  True  True]


### **copy and view**

In [12]:
import numpy as np
arr = np.array([10,20,30,40,50,60])
arr2 = arr[1:4].copy()
arr3 = arr[2:5].view()
arr2[1] = 100
print("Output using copy(): ",arr)
arr3[1] = 600
print("Output using view(): ",arr)

Output using copy():  [10 20 30 40 50 60]
Output using view():  [ 10  20  30 600  50  60]


In [52]:
import numpy as np

arr1 = np.zeros((5,3),dtype=np.int8)+9
arr2 = np.ones((5,3),dtype=np.int8)+9
arr3 = np.eye(3)
arr4 = np.diag((7,10,12,34,56))
rno = np.random.randint(0,10,8)
r = np.random.rand(2,3)

print(arr1,"\n\n",arr2,"\n\n",arr3,"\n\n",arr4,"\n\n",rno,"\n\n",r)

[[9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]] 

 [[10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]] 

 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

 [[ 7  0  0  0  0]
 [ 0 10  0  0  0]
 [ 0  0 12  0  0]
 [ 0  0  0 34  0]
 [ 0  0  0  0 56]] 

 [3 8 4 6 3 3 2 4] 

 [[0.33144443 0.23143554 0.61205716]
 [0.75442009 0.27486297 0.58395138]]


### **reshape()**

In [62]:
import numpy as np

arr = np.array([10,20,30,40,50,60])
arr1 = arr.reshape(2,3)
arr2 = arr.reshape(-1,1,2)
arr3 = arr.reshape(2,-1)

print("Array 1 : ",arr1,"\n\nArray 2 : ",arr2,"\n\nArray 3 : ",arr3)

Array 1 :  [[10 20 30]
 [40 50 60]] 

Array 2 :  [[[10 20]]

 [[30 40]]

 [[50 60]]] 

Array 3 :  [[10 20 30]
 [40 50 60]]


### **random.seed()**

In [87]:
import numpy as np

np.random.seed(134567)
randno = np.random.randint(1,500,30).reshape(6,5)
print(randno)
print(randno[2:,2:])
print(randno[3:5,2:4])



[[ 98 428 286 389  49]
 [206   5 298  80 234]
 [ 33 298 312  73 297]
 [240 406 370 466 329]
 [431 140 463 292 122]
 [ 56 311 169 482  90]]
[[312  73 297]
 [370 466 329]
 [463 292 122]
 [169 482  90]]
[[370 466]
 [463 292]]
<class 'numpy.ndarray'>
[0 0]
[10 20 30 40  0  0]


### **Slicing in ndarray**

In [96]:
arr = np.array([10,20,30,40,50,60,1,2,3,4,9,33,])
slicing = arr[4:9]
print("sliced array : ",slicing)
print("Array: ",arr)
print("Type of Sliced Array: ",type(slicing))
print("Type of Array: ",type(arr))
slicing[:] = 0
print("New Slicing: ",slicing)
print("formatted Array : ",arr)

sliced array :  [50 60  1  2  3]
Array:  [10 20 30 40 50 60  1  2  3  4  9 33]
Type of Sliced Array:  <class 'numpy.ndarray'>
Type of Array:  <class 'numpy.ndarray'>
New Slicing:  [0 0 0 0 0]
formatted Array :  [10 20 30 40  0  0  0  0  0  4  9 33]
