## **Numpy**<hr/>

NumPy, which stands for **"Numerical Python,"** is a popular Python library for numerical and scientific computing. It provides support for working with large, multi-dimensional arrays and matrices of data, along with a collection of mathematical functions to operate on these arrays.

NumPy is a fundamental library for data manipulation and analysis in Python and is widely used in various fields such as data science, machine learning, scientific research, and engineering.

### **ndim**<hr/>

it is used to get the dimension of the array

In [13]:
import numpy as ny

a = ny.array(42)
b = ny.array([1,2,3,4,5])
c = ny.array([[1,2,3],[4,5,6]])

print(a.ndim)
print(b.ndim)
print(c.ndim)

print(a)
print(b)
print(c)


0
1
2
42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### **shape**<hr/>

It is used to provide the dimensions of the array

In [14]:
import numpy as ny

a = ny.array(42)
b = ny.array([1,2,3,4,5])
c = ny.array([[1,2,3],[4,5,6]])
d = ny.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)


()
(5,)
(2, 3)
(2, 2, 3)


In [54]:
import numpy as np

arr = np.array([True,False,True],dtype = np.int32)
print(arr)

[1 0 1]


In [49]:
import numpy as np

arr = np.array(['apple',1,2.3],dtype = np.bool_)
print(arr)

[ True  True  True]
