## ***Numpy***<hr/>

NumPy, which stands for **"Numerical Python,"** is a popular Python library for numerical and scientific computing. It provides support for working with large, multi-dimensional arrays and matrices of data, along with a collection of mathematical functions to operate on these arrays.

NumPy is a fundamental library for data manipulation and analysis in Python and is widely used in various fields such as data science, machine learning, scientific research, and engineering.

### ***ndim***<hr/>

it is used to get the dimension of the array

In [42]:
import numpy as ny

a = ny.array(42)
b = ny.array([1,2,3,4,5])
c = ny.array([[1,2,3],[4,5,6]])

print(a.ndim)
print(b.ndim)
print(c.ndim)

print(a)
print(b)
print(c)


0
1
2
42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### ***shape***<hr/>

It is used to provide the dimensions of the array

In [43]:
import numpy as ny

a = ny.array(42)
b = ny.array([1,2,3,4,5])
c = ny.array([[1,2,3],[4,5,6]])
d = ny.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)


()
(5,)
(2, 3)
(2, 2, 3)


In [44]:
import numpy as np

arr = np.array([True,False,True],dtype = np.int32)
print(arr)

[1 0 1]


In [45]:
import numpy as np

arr = np.array(['apple',1,2.3],dtype = np.bool_)
print(arr)

[ True  True  True]


### ***copy and view***

In [46]:
import numpy as np
arr = np.array([10,20,30,40,50,60])
arr2 = arr[1:4].copy()
arr3 = arr[2:5].view()
arr2[1] = 100
print("Output using copy(): ",arr)
arr3[1] = 600
print("Output using view(): ",arr)

Output using copy():  [10 20 30 40 50 60]
Output using view():  [ 10  20  30 600  50  60]


In [47]:
import numpy as np

arr1 = np.zeros((5,3),dtype=np.int8)+9
arr2 = np.ones((5,3),dtype=np.int8)+9
arr3 = np.eye(3)
arr4 = np.diag((7,10,12,34,56))
rno = np.random.randint(0,10,8)
r = np.random.rand(2,3)

print(arr1,"\n\n",arr2,"\n\n",arr3,"\n\n",arr4,"\n\n",rno,"\n\n",r)

[[9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]] 

 [[10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]] 

 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

 [[ 7  0  0  0  0]
 [ 0 10  0  0  0]
 [ 0  0 12  0  0]
 [ 0  0  0 34  0]
 [ 0  0  0  0 56]] 

 [5 4 4 5 7 3 6 4] 

 [[0.58679698 0.71975423 0.25849809]
 [0.54620732 0.40730783 0.17698462]]


### ***reshape()***

In [48]:
import numpy as np

arr = np.array([10,20,30,40,50,60])
arr1 = arr.reshape(2,3)
arr2 = arr.reshape(-1,1,2)
arr3 = arr.reshape(2,-1)

print("Array 1 : ",arr1,"\n\nArray 2 : ",arr2,"\n\nArray 3 : ",arr3)

Array 1 :  [[10 20 30]
 [40 50 60]] 

Array 2 :  [[[10 20]]

 [[30 40]]

 [[50 60]]] 

Array 3 :  [[10 20 30]
 [40 50 60]]


### ***random.seed()***

In [49]:
import numpy as np

np.random.seed(134567)
randno = np.random.randint(1,500,30).reshape(6,5)
print(randno)
print(randno[2:,2:])
print(randno[3:5,2:4])



[[ 98 428 286 389  49]
 [206   5 298  80 234]
 [ 33 298 312  73 297]
 [240 406 370 466 329]
 [431 140 463 292 122]
 [ 56 311 169 482  90]]
[[312  73 297]
 [370 466 329]
 [463 292 122]
 [169 482  90]]
[[370 466]
 [463 292]]


### ***Slicing in ndarray***

In [50]:
arr = np.array([10,20,30,40,50,60,1,2,3,4,9,33,])
slicing = arr[4:9]
print("sliced array : ",slicing)
print("Array: ",arr)
print("Type of Sliced Array: ",type(slicing))
print("Type of Array: ",type(arr))
slicing[:] = 0
print("New Slicing: ",slicing)
print("formatted Array : ",arr)

sliced array :  [50 60  1  2  3]
Array:  [10 20 30 40 50 60  1  2  3  4  9 33]
Type of Sliced Array:  <class 'numpy.ndarray'>
Type of Array:  <class 'numpy.ndarray'>
New Slicing:  [0 0 0 0 0]
formatted Array :  [10 20 30 40  0  0  0  0  0  4  9 33]


### ***Arithmetic operations on array***

In [51]:
import numpy as np

arr = np.arange(1,15)

print("All the Elements of array are : ",*arr)
print("twice of each number : ",*arr*2)
print("Square of each number : ",*arr**2)

print("All the even numbers in the array : ",*arr[arr%2 == 0])
print("Odd numbers of the array : ",*arr[arr%2!=0])
print("Numbers that are greater than 8 : ",*arr[arr>8])
arr[arr%2==0]=0
print("final array : ",*arr)
print("----------------------------------------------------------------------------------")

nos = np.array([10,20,30,25,60,70,82])
print("Minimum of the array : ",np.min(nos))
print("Maximum of the array : ",np.max(nos))
print("Argmin of the array : ",np.argmin(nos))
print("Argmax of the array : ",np.argmax(nos))
print("Square root of the numbers of array : ",", ".join(f"{x:.2f}"for x in np.sqrt(nos)))
print("Sine of each number of the array : ",", ".join(f"{y:.2f}"for y in np.sin(nos)))
print("Cosine of each number of the array : ",", ".join(f"{z:.2f}"for z in np.cos(nos)))

print("----------------------------------------------------------------------------------")

np.random.seed(2)
mat = np.random.randint(1,21,9).reshape(3,3)
print(mat) 
print("\n",np.sum(mat))
print("\n",np.cumsum(mat))
print("\n",np.min(mat))
print("\n",np.max(mat))
print("----------------------------------------------------------------------------------")
print("\n",np.sum(mat,axis=1))
print("\n",np.min(mat,axis=1))
print("\n",np.max(mat,axis=1))
print("\n",np.cumsum(mat,axis=1))



All the Elements of array are :  1 2 3 4 5 6 7 8 9 10 11 12 13 14
twice of each number :  2 4 6 8 10 12 14 16 18 20 22 24 26 28
Square of each number :  1 4 9 16 25 36 49 64 81 100 121 144 169 196
All the even numbers in the array :  2 4 6 8 10 12 14
Odd numbers of the array :  1 3 5 7 9 11 13
Numbers that are greater than 8 :  9 10 11 12 13 14
final array :  1 0 3 0 5 0 7 0 9 0 11 0 13 0
----------------------------------------------------------------------------------
Minimum of the array :  10
Maximum of the array :  82
Argmin of the array :  0
Argmax of the array :  6
Square root of the numbers of array :  3.16, 4.47, 5.48, 5.00, 7.75, 8.37, 9.06
Sine of each number of the array :  -0.54, 0.91, -0.99, -0.13, -0.30, 0.77, 0.31
Cosine of each number of the array :  -0.84, 0.41, 0.15, 0.99, -0.95, 0.63, 0.95
----------------------------------------------------------------------------------
[[ 9 16 14]
 [ 9 12 19]
 [12  9  8]]

 108

 [  9  25  39  48  60  79  91 100 108]

 8

 19
----

### ***self_defined funtion to perform cumsum***

In [10]:
import numpy as np

np.random.seed(2)
mat2 = np.random.randint(1,21,(3,3))
print("original array :",mat2)
def allsum(arr):
    cumsum_arr = 0
    final_arr = []
    for i in range(arr.shape[0]):
        for j in range(arr.shape[0]):
            cumsum_arr += arr[i][j]
            final_arr.append(cumsum_arr)
        cumsum_arr = 0
    return np.array(final_arr)
result = allsum(mat2).reshape(3,3)
print("Cumsum of the array : ",result)



original array : [[ 9 16 14]
 [ 9 12 19]
 [12  9  8]]
Cumsum of the array :  [[ 9 25 39]
 [ 9 21 40]
 [12 21 29]]


### ***unique***

In [53]:
import numpy as np

np.random.seed(2)
arr = np.random.randint(1,20,10)

print(arr)
print(np.unique(arr,return_index=True,return_counts=True))

[ 9 16 14  9 12 19 12  9  8  3]
(array([ 3,  8,  9, 12, 14, 16, 19]), array([9, 8, 0, 4, 2, 1, 5], dtype=int64), array([1, 1, 3, 2, 1, 1, 1], dtype=int64))


### ***vstack***

In [54]:
import numpy as np

arr1 = np.array([10,20,30,40])
arr2 = np.array([50,60,70,80])
mat1 = np.random.randint(1,30,9).reshape(3,3)
mat2 = np.random.randint(30,50,9).reshape(3,3)
print("Array 1 : ",arr1)
print("Array 2 :",arr2)
print("vstack of arrays :\n",np.vstack((arr1,arr2)))
print("hstack of arrays :\n",np.hstack((arr1,arr2)))
print("---------------------------------------")
print("vstack of matrices :\n",np.vstack((mat1,mat2)))
print("hstack of matrices :\n",np.hstack((mat1,mat2)))


Array 1 :  [10 20 30 40]
Array 2 : [50 60 70 80]
vstack of arrays :
 [[10 20 30 40]
 [50 60 70 80]]
hstack of arrays :
 [10 20 30 40 50 60 70 80]
---------------------------------------
vstack of matrices :
 [[18 12 22]
 [16 27 21]
 [29 21  6]
 [37 33 36]
 [34 40 41]
 [49 37 36]]
hstack of matrices :
 [[18 12 22 37 33 36]
 [16 27 21 34 40 41]
 [29 21  6 49 37 36]]


### ***searchsorted()***

In [13]:
import numpy as np

np.random.seed(2)
arr = np.random.randint(1,100,10)
ss = np.searchsorted(arr,30)
print(f"{arr} \n {ss}")

[41 16 73 23 44 83 76  8 35 50] 
 2


### ***Transpose()***

In [9]:
import numpy as np

arr = np.array([[1,2,3,4,5],[1,3,56,7,5]])
print("Array is : ",arr)

Np_Trans = np.transpose(arr)
print("Transpose of array is: ",Np_Trans)

[[ 1  2  3  4  5]
 [ 1  3 56  7  5]]
[[ 1  1]
 [ 2  3]
 [ 3 56]
 [ 4  7]
 [ 5  5]]


### ***np.mean()***

In [24]:
import numpy as np

arr = np.array([1,2,3,4,5])

Np_Mean = np.mean(arr)
print("Mean of array: ",Np_Mean)

Mean of array:  3.0


### ***np.extract()***

In [20]:
import numpy as np

arr = np.array([1,2,3,4,5])

Np_extract = np.extract(arr>2,arr)
print(Np_extract)

[3 4 5]


### ***np.sort()***

In [21]:
import numpy as np

arr= np.array([1,3,4,2,0,6])
sorted = np.sort(arr)
sorted_inverse = np.sort(arr)[::-1]
print("Sorting in ascending order: ",sorted)
print("Sorting in descending order: ",sorted_inverse)

Sorting in ascending order:  [0 1 2 3 4 6]
Sorting in descending order:  [6 4 3 2 1 0]


### ***np.split***

In [23]:
import numpy as np

arr = np.array([1,23,45,789,23,56])

sub_arrays = np.split(arr,3)
for sub_array in sub_arrays:
    print(sub_array)

[ 1 23]
[ 45 789]
[23 56]
